# Site settings
title: "Villa Vogelenzang"
email: "yasmine@villavogelenzang.be"
description: "Villa Vogelenzang | Paardrijden en kinderboerderij"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: "VVogelenzang"
facebook_username: "VillaVogelenzang"

# Build settings
markdown: kramdown
